version: 1
frontend:
  phases:
    preBuild:
      commands:
        - echo "Starting build process"
        - echo "Node version $(node -v)"
        - echo "NPM version $(npm -v)"
        - npm ci --legacy-peer-deps
    build:
      commands:
        - echo "Starting build"
        - npm run build
        - echo "Build completed"
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
