version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - echo "Installing dependencies"
        - npm install --legacy-peer-deps
    build:
      commands:
        - echo "Starting build"
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
